version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=fast-tour
      - POSTGRES_USER=gaston
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5050:80
